### ISSUE TITLE
Help needed - adding algorithms not listed in the README

### ISSUE THREAD

**Issue by singhayushh** [singhayushh/book_CLRS#1]
### The Issue
Help me make an extensive list of data structures and algorithms

As on 11/09/2020, 
The [README.md](https://github.com/singhayushh/book_CLRS/blob/master/README.md) file has a total of 64 algorithms listed. I am looking for contributions to this list to help me have an extensive list of data structures and algorithms

### How to contribute
Just add names of data structures / algorithms that aren't already listed in the README Table

> Kindly do not send PRs with source codes!
I am looking for help to make an extensive list of algorithms in the Readme. I would prefer to code them out myself 😅

**Comment by uditswaroopa** [comment]
Hey, I can help you!

**Comment by singhayushh** [comment]
@uditswaroopa 
Thanks for showing up. 
If you're targeting hacktober fest, you may contribute after October 1st, I'm in no hurries 😁

**Comment by Any28Flo** [comment]
hey, do you need help with this? I can help you with this issue

**Comment by singhayushh** [comment]
> hey, do you need help with this? I can help you with this issue

@Any28Flo
Yes I do need help with this!

**Comment by deytulsi18** [comment]
Can I help you.
I will add Subset Sum solution in Java

**Comment by singhayushh** [comment]
This is to notify that I am no longer accepting PRs for solutions to any of the algorithms. Please go through the issues for open source contribution.

**Comment by deytulsi18** [comment]
I have updated the READMe.md and added more algos to the list.
kindly merge the PR  to the master

**Comment by singhayushh** [comment]
Merged to master.
Thanks!

**Comment by deytulsi18** [comment]
Welcome
I would love to help you if I can ,by any other ways too.
😁
